### About Dataset

- Context This is a small subset of dataset of Book reviews from Amazon Kindle Store category.

- Content 5-core dataset of product reviews from Amazon Kindle Store category from May 1996 - July 2014. Contains total of 982619 entries. Each reviewer has at least 5 reviews and each product has at least 5 reviews in this dataset.

#### Columns

- asin - ID of the product, like B000FA64PK
- helpful - helpfulness rating of the review - example: 2/3.
- overall - rating of the product.
- reviewText - text of the review (heading).
- reviewTime - time of the review (raw).
- reviewerID - ID of the reviewer, like A3SPTOKDG7WBLN
- reviewerName - name of the reviewer.
- summary - summary of the review (description).
- unixReviewTime - unix timestamp.
- Acknowledgements This dataset is taken from Amazon product data, Julian McAuley, UCSD website. http://jmcauley.ucsd.edu/data/amazon/
- License to the data files belong to them.

#### Inspiration

- Sentiment analysis on reviews.
- Understanding how people rate usefulness of a review/ What factors influence helpfulness of a review.
- Fake reviews/ outliers.
- Best rated product IDs, or similarity between products based on reviews alone (not the best idea ikr).
- Any other interesting analysis
- Best Practises

#### Preprocessing And Cleaning

- Train Test Split
- BOW,TFIDF,Word2vec
- Train ML algorithms

##### Best Practices 
- Preprocessing and Cleaning
- Train Test Split
- BOW , TFIDF , Word2Vec
- Train ML Algorithms

In [53]:
# Loading of dataset
import pandas as pd

data = pd.read_csv('file.csv')

In [54]:
data.tail(4)

Unnamed: 0.1  Unnamed: 0        asin helpful  rating  \
11996         11996        6272  B002JCSFSQ  [2, 2]       5   
11997         11997       12483  B0035N1V7K  [0, 1]       3   
11998         11998        3640  B001W1XT40  [1, 2]       1   
11999         11999       11398  B003370JUS  [5, 6]       3   

                                              reviewText   reviewTime  \
11996  I have read all seven books in this series. Ap...  05 16, 2011   
11997  This book really just wasn't my cuppa.  The si...  07 26, 2013   
11998  tried to use it to charge my kindle, it didn't...  09 17, 2013   
11999  Taking Instruction is a look into the often hi...   07 5, 2012   

           reviewerID                   reviewerName  \
11996   AQRSPXLNEQAMA                        TerryLP   
11997  A2T5QLT5VXOJAK                        hwilson   
11998  A28MHD2DDY6DXB  Allison A. Slater "Gryphon50"   
11999  A3JUXLB4K9ZXCC                      Dafna Yee   

                                                 summary  unixReviewTime  
11996                                Peacekeepers Series      1305504000  
11997                                    a little creepy      1374796800  
11998                                        didn't work      1379376000  
11999  If you like BDSM with a touch of romance, this...      1341446400

In [55]:
data = data[['reviewText' , 'rating']]
data.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [4]:
data.shape

(12000, 2)

In [56]:
# to count the total null values
data.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [57]:
# to know unique rating are there
data['rating'].unique()

array([3, 5, 4, 2, 1], dtype=int64)

In [58]:
# to check if imbalanced dataset or not
data['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

#### Preprocessing and Cleaning
- here if the rating is less than three then that will be categories as bad review
- if the raing is more than three then good review

In [59]:
data['rating'] = data['rating'].apply(lambda x: 0 if x < 3 else 1)   # if x > 3 then 1 or else 0

In [60]:
data['rating'].unique()

array([1, 0], dtype=int64)

In [61]:
data['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [62]:
## Now lower all the cases
data['reviewText'] = data['reviewText'].str.lower()

In [63]:
data.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [64]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\91993/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [19]:
!pip install beautifulsoup4

Defaulting to user installation because normal site-packages is not writeable
  Using cached beautifulsoup4-4.13.3-py3-none-any.whl.metadata (3.8 kB)
  Using cached soupsieve-2.6-py3-none-any.whl.metadata (4.6 kB)
Using cached beautifulsoup4-4.13.3-py3-none-any.whl (186 kB)
Using cached soupsieve-2.6-py3-none-any.whl (36 kB)


In [65]:
from bs4 import BeautifulSoup

In [24]:
!pip install lxml --force-reinstall

Defaulting to user installation because normal site-packages is not writeable
  Using cached lxml-5.3.1-cp310-cp310-win_amd64.whl.metadata (3.8 kB)
Using cached lxml-5.3.1-cp310-cp310-win_amd64.whl (3.8 MB)
  Attempting uninstall: lxml
    Found existing installation: lxml 5.3.1
    Uninstalling lxml-5.3.1:
      Successfully uninstalled lxml-5.3.1


In [66]:
## Removing special characters
data['reviewText']=data['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
data['reviewText']=data['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url 
data['reviewText']=data['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove any additional spaces
data['reviewText']=data['reviewText'].apply(lambda x: " ".join(x.split()))

In [67]:
data

reviewText  rating
0      jace rankin may short hes nothing mess man hau...       1
1      great short read didnt want put read one sitti...       1
2      ill start saying first four books wasnt expect...       1
3      aggie angela lansbury carries pocketbooks inst...       1
4      expect type book library pleased find price right       1
...                                                  ...     ...
11995  valentine cupid vampire- jena ian another vamp...       1
11996  read seven books series apocalypticadventure o...       1
11997  book really wasnt cuppa situation man capturin...       1
11998  tried use charge kindle didnt even register ch...       0
11999  taking instruction look often hidden world sex...       1

[12000 rows x 2 columns]

In [68]:
### Now doing Lemmatizer
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [69]:
def lemmatize_word(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [70]:
data['reviewText']=data['reviewText'].apply(lambda x: lemmatize_word(x))

In [71]:
data.head()

reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [32]:
## Train test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( data['reviewText'] , data['rating'] , test_size=0.2 , random_state=42 )

# X will be data['reviewText']
# y will be data['rating']

In [37]:
from sklearn.feature_extraction.text import CountVectorizer   # BOW
bow = CountVectorizer()
X_train_bow = bow.fit_transform(X_train).toarray()
X_test_bow = bow.transform(X_test).toarray()

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer   # TFIDF
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()

In [39]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [42]:
# Apply Naive Bayes algorithm because it fits more with sparse matrix 
from sklearn.naive_bayes import GaussianNB
nb_model_bow = GaussianNB().fit(X_train_bow , y_train)
nb_model_tfidf = GaussianNB().fit(X_train_tfidf , y_train)

In [44]:
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix

In [45]:
y_pred_bow = nb_model_bow.predict(X_test_bow)

In [46]:
y_pred_tfidf = nb_model_tfidf.predict(X_test_tfidf)

In [47]:
confusion_matrix(y_test , y_pred_bow)

array([[499, 304],
       [717, 880]], dtype=int64)

In [48]:
print('Accuracy of BOW : ' , accuracy_score(y_test , y_pred_bow))

Accuracy of BOW :  0.5745833333333333


In [49]:
confusion_matrix(y_test , y_pred_tfidf)

array([[488, 315],
       [696, 901]], dtype=int64)

In [50]:
print('Accuracy of TFIDF : ' , accuracy_score(y_test , y_pred_tfidf))

Accuracy of TFIDF :  0.57875


In [51]:
classification_report(y_test , y_pred_bow)

'              precision    recall  f1-score   support\n\n           0       0.41      0.62      0.49       803\n           1       0.74      0.55      0.63      1597\n\n    accuracy                           0.57      2400\n   macro avg       0.58      0.59      0.56      2400\nweighted avg       0.63      0.57      0.59      2400\n'

In [52]:
classification_report(y_test , y_pred_tfidf)

'              precision    recall  f1-score   support\n\n           0       0.41      0.61      0.49       803\n           1       0.74      0.56      0.64      1597\n\n    accuracy                           0.58      2400\n   macro avg       0.58      0.59      0.57      2400\nweighted avg       0.63      0.58      0.59      2400\n'

### Now Doing with Word2Vec , AvgWord2Vec

In [72]:
X_train, X_test, y_train, y_test = train_test_split(data['reviewText'], data['rating'], test_size=0.2, random_state=42)

In [74]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from gensim.models import Word2Vec
from tqdm import tqdm

In [76]:
import numpy as np

def avg_word2vec(sentence, model, vector_size=100):
    """Compute the average Word2Vec vector for a given sentence."""
    vector = np.zeros(vector_size)  # Initialize vector with zeros
    word_count = 0
    
    for word in sentence:
        if word in model.wv:  # Check if the word is in Word2Vec vocabulary
            vector += model.wv[word]  # Add word vector
            word_count += 1  # Count words found in vocabulary
    
    if word_count > 0:
        vector /= word_count  # Compute mean (avoid division by zero)
    
    return vector


In [77]:
# Convert training data
X_train_w2v = np.array([avg_word2vec(sentence, w2v_model) for sentence in X_train])

# Convert test data
X_test_w2v = np.array([avg_word2vec(sentence, w2v_model) for sentence in X_test])

print(X_train_w2v.shape, X_test_w2v.shape)  # Check dimensions


(9600, 100) (2400, 100)


In [78]:
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train_w2v, y_train)


RandomForestClassifier(random_state=42)

In [79]:
y_pred = clf.predict(X_test_w2v)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")


Model Accuracy: 0.6675
