## BOW , TFIDF , Marchine Learning Algorithms

In [32]:
import pandas as pd
messages = pd.read_csv('file.csv', sep='\t', names=["label", "message"])

In [33]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [52]:
import re    # regular expression
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\91993/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [53]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [54]:
corpus = []

for i in range(0 ,len(messages)):
    review = re.sub('[^a-zA-Z]' , ' ' , messages['message'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

#### BOW - Bag of Words

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500 , ngram_range=(1,2))

In [ ]:
# Independent Features
X = cv.fit_transform(corpus).toarray()

In [11]:
import numpy as np
np.set_printoptions(edgeitems=30 ,linewidth=100000 , formatter=dict(float=lambda x: "%.3f" % x))
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [12]:
cv.vocabulary_

{'go': 795,
 'point': 1607,
 'crazi': 456,
 'avail': 114,
 'bugi': 225,
 'great': 852,
 'world': 2429,
 'la': 1103,
 'cine': 352,
 'got': 840,
 'wat': 2337,
 'ok': 1481,
 'lar': 1114,
 'joke': 1071,
 'wif': 2395,
 'free': 709,
 'entri': 612,
 'wkli': 2419,
 'comp': 406,
 'win': 2400,
 'cup': 471,
 'final': 677,
 'st': 1979,
 'may': 1269,
 'text': 2083,
 'receiv': 1704,
 'question': 1665,
 'std': 1992,
 'txt': 2196,
 'rate': 1682,
 'appli': 78,
 'free entri': 714,
 'entri wkli': 614,
 'std txt': 1993,
 'txt rate': 2202,
 'rate appli': 1684,
 'dun': 573,
 'say': 1803,
 'earli': 579,
 'alreadi': 50,
 'nah': 1392,
 'think': 2103,
 'goe': 815,
 'usf': 2270,
 'live': 1178,
 'around': 90,
 'though': 2111,
 'freemsg': 721,
 'hey': 927,
 'darl': 487,
 'week': 2363,
 'word': 2425,
 'back': 131,
 'like': 1164,
 'fun': 743,
 'still': 1995,
 'tb': 2063,
 'xxx': 2465,
 'send': 1838,
 'even': 622,
 'brother': 214,
 'speak': 1963,
 'treat': 2170,
 'per': 1550,
 'request': 1741,
 'mell': 1281,
 'oru': 

In [47]:
# Output or Dependent Features
y = pd.get_dummies(messages['label'])


In [49]:
y = y.iloc[:,0].values

In [50]:
y

array([ True,  True, False,  True,  True, False,  True,  True, False, False,  True, False, False,  True,  True, False,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True,  True,  True,  True])

In [24]:
# Train and test split
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.20 , random_state=30)

In [25]:
# X_train and y_train are my independent features and dependent features
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train , y_train)

In [26]:
spam_detect_model 

MultinomialNB()

In [28]:
y_pred = spam_detect_model.predict(X_test)

In [ ]:
# to compare
from sklearn.metrics import accuracy_score , classification_report
accuracy = accuracy_score(y_test , y_pred)   # this will get compare but we will analyse it with classification reports 

In [30]:
accuracy

0.9847533632286996

In [31]:
from sklearn.metrics import classification_report
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

       False       0.95      0.92      0.94       136
        True       0.99      0.99      0.99       979

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115



## TF-IDF Model

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500 , ngram_range=(1,2))

In [38]:
X = tv.fit_transform(corpus).toarray()

In [39]:
X

array([[0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, ..., 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, ..., 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000

In [40]:
tv.vocabulary_

{'go': 795,
 'point': 1607,
 'crazi': 456,
 'avail': 114,
 'bugi': 225,
 'great': 852,
 'world': 2429,
 'la': 1103,
 'cine': 352,
 'got': 840,
 'wat': 2337,
 'ok': 1481,
 'lar': 1114,
 'joke': 1071,
 'wif': 2395,
 'free': 709,
 'entri': 612,
 'wkli': 2419,
 'comp': 406,
 'win': 2400,
 'cup': 471,
 'final': 677,
 'st': 1979,
 'may': 1269,
 'text': 2083,
 'receiv': 1704,
 'question': 1665,
 'std': 1992,
 'txt': 2196,
 'rate': 1682,
 'appli': 78,
 'free entri': 714,
 'entri wkli': 614,
 'std txt': 1993,
 'txt rate': 2202,
 'rate appli': 1684,
 'dun': 573,
 'say': 1803,
 'earli': 579,
 'alreadi': 50,
 'nah': 1392,
 'think': 2103,
 'goe': 815,
 'usf': 2270,
 'live': 1178,
 'around': 90,
 'though': 2111,
 'freemsg': 721,
 'hey': 927,
 'darl': 487,
 'week': 2363,
 'word': 2425,
 'back': 131,
 'like': 1164,
 'fun': 743,
 'still': 1995,
 'tb': 2063,
 'xxx': 2465,
 'send': 1838,
 'even': 622,
 'brother': 214,
 'speak': 1963,
 'treat': 2170,
 'per': 1550,
 'request': 1741,
 'mell': 1281,
 'oru': 

In [41]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.20 , random_state=30)


In [42]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train , y_train)

In [43]:
y_pred = spam_tfidf_model.predict(X_test)

In [44]:
score = accuracy_score(y_test , y_pred)

In [45]:
score

0.9766816143497757

In [46]:
from sklearn.metrics import classification_report
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

       False       0.99      0.82      0.90       136
        True       0.98      1.00      0.99       979

    accuracy                           0.98      1115
   macro avg       0.98      0.91      0.94      1115
weighted avg       0.98      0.98      0.98      1115



- But the mistake here in above program is , we have done train_test_split after BOW and TFIDF and it is to be done in before steps .

- This is beacuse if we do train_test_split in first , then model have no idea regarding the test and the correct prediction will be taken .
- Now if we do TF-IDF , some data regrading the test is already known so the prediction percentage will be high but it will fail in rel world problems .
- By doing this we are preventing the data leakage .

In [51]:
import pandas as pd
messages = pd.read_csv('file.csv', sep='\t', names=["label", "message"])

In [70]:
corpus = []

for i in range(0 ,len(messages)):
    review = re.sub('[^a-zA-Z]' , ' ' , messages['message'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [71]:
# Train and test split
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(corpus , y , test_size=0.20 , random_state=30)

In [72]:
# Now applying BOW here .
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500 , ngram_range=(1,2))

In [73]:
# Independent Features
X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray()

In [74]:
import numpy as np
np.set_printoptions(edgeitems=30 ,linewidth=100000 , formatter=dict(float=lambda x: "%.3f" % x))
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [75]:
cv.vocabulary_

{'today': 2148,
 'sorri': 1941,
 'day': 495,
 'ever': 631,
 'angri': 67,
 'hurt': 995,
 'plz': 1595,
 'urself': 2276,
 'bcoz': 157,
 'ur': 2246,
 'fault': 670,
 'basic': 152,
 'good': 825,
 'alway': 61,
 'celebr': 318,
 'famili': 661,
 'boo': 200,
 'time': 2129,
 'get': 773,
 'suppos': 2039,
 'take': 2051,
 'shop': 1864,
 'time get': 2132,
 'fuck': 746,
 'chicken': 340,
 'messag': 1297,
 'would': 2445,
 'late': 1119,
 'hear': 913,
 'word': 2434,
 'lol': 1196,
 'play': 1584,
 'door': 567,
 'sometim': 1932,
 'yo': 2492,
 'thank': 2094,
 'talk': 2056,
 'saturday': 1794,
 'dear': 505,
 'brother': 226,
 'role': 1762,
 'model': 1347,
 'rington': 1757,
 'club': 368,
 'uk': 2222,
 'singl': 1889,
 'mobil': 1334,
 'week': 2367,
 'choos': 348,
 'top': 2165,
 'qualiti': 1665,
 'free': 720,
 'charg': 330,
 'ye': 2478,
 'mum': 1384,
 'lookin': 1204,
 'friendship': 742,
 'game': 756,
 'say': 1800,
 'start': 1979,
 'march': 1262,
 'end': 608,
 'may': 1280,
 'tomorrow': 2156,
 'yesterday': 2489,
 'offi

In [76]:
y = pd.get_dummies(messages['label'])
y = y.iloc[:,0].values

In [77]:
# X_train and y_train are my independent features and dependent features
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train , y_train)

In [78]:
y_pred = spam_detect_model.predict(X_test)

In [79]:
score = accuracy_score(y_test , y_pred)

In [80]:
score

0.9847533632286996

In [81]:
from sklearn.metrics import classification_report
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

       False       0.95      0.92      0.94       136
        True       0.99      0.99      0.99       979

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115

